version: '3'

services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/base:jammy
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    entrypoint: /usr/local/share/docker-init.sh
    command: sleep infinity 