version: '3'

services:
  harness-core-ui:
    image: node:16  # Base image for the Node.js service
    container_name: harness-core-ui
    volumes:
      - ./harness-core-ui:/workspace/harness-core-ui  # Bind mount for harness-core-ui
    working_dir: /workspace/harness-core-ui
    command: >
      /bin/bash -c "
      if [ ! -d /workspace/harness-core-ui ]; then
        git clone https://github.com/harness/harness-core-ui /workspace/harness-core-ui;
      fi
      yarn install && yarn dev
      "

  cde-ui:
    image: node:16  # Base image for the CDE service
    container_name: cde-ui
    volumes:
      - ./gitness-cde:/workspace/gitness-cde  # Bind mount for gitness-cde
    working_dir: /workspace/gitness-cde
    command: >
      /bin/bash -c "
      if [ ! -d /workspace/gitness-cde ]; then
        git clone https://github.com/deepesh-ui/gitness-cde /workspace/gitness-cde;
      fi
      cd web && yarn install && yarn dev:cde
      "
